---
title: "Flexdashboard"
author: "JAT"
date: "29/10/2021"
output: html_document
---


```{r}
#install.packages("flexdashboard")
#install.packages("rmarkdown")

#https://garrettgman.github.io/rmarkdown/rmarkdown_websites.html
#https://rstudio.github.io/flexdashboard/articles/examples.html


#Thanks for the inspiration to:
#https://www.r-bloggers.com/2020/09/deploying-flexdashboard-on-github-pages/
#https://ramikrispin.github.io/flexdashboard_example/
```


#```{r}



#rmarkdown::draft("index.Rmd", template = "flex_dashboard", package = "flexdashboard")
#```


```{r}

#install.packages("flexdashboard", type = "source")

#install.packages("rmarkdown", type = "source")

#Remember to have on the same folder the file: _site.yml

# render the entire site
#rmarkdown::render_site()

wd<-dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(wd)

# render a single file only
rmarkdown::render_site("index.Rmd")

rmarkdown::run("index.Rmd", shiny_args = list(port = 3838, host = "0.0.0.0"))
#Then you reach the dashboard in your webbrowser via 
#http://localhost:3838 
#or any other host and port you defined via shiny_args.

```