---
title: "Stock_returns_interactive"
author: "JAT"
date: "24/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r install packages}

install.packages("cat")
library("cat")

cat("\014") # clear saved variables
cat("\f");

install.packages("BatchGetSymbols")
install.packages("readxl")
install.packages("ggplot2")
install.packages("reshape2")
install.packages("rstudioapi")
install.packages("quantmod")
install.packages("dplyr")
install.packages("lubridate")

#install.packages("na.tools")
#library("na.tools")


install.packages("shiny")
install.packages("shinythemes")
install.packages("shinyWidgets")
install.packages("DT")


install.packages("ggthemes")
install.packages("plotly")

cat("\f") # clear console

```


```{r libraries}

library("BatchGetSymbols")
library("readxl")
library("ggplot2")
library("reshape2")
library("rstudioapi")
library("quantmod")
library("dplyr")
library("lubridate")

cat("\014")
cat("\f")


# For Shiny

library(shiny)
library(shinythemes)
library(shinyWidgets)



library(DT)

library(ggthemes)
library(plotly)

require(dplyr)
             library(dplyr)    
library(plyr)



library("priceR") #inflation / currency exchange


# DIRECTORY:

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()

```




```{r read from excel}

# set as direction the one of .Rmd archive; .xlsx and .Rmd mut be on same folder
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

my_data <- read_excel("Bolsa.xlsx", sheet="Datos para R")

# clear empty cells in my_data; overwrite it
my_data <- na.omit(my_data)

```


```{r inflation data}




Year <- 1970:2020
#nominal_prices <- rnorm(10, mean=10, sd=3)
nominal_prices <- rep(1,length(Year))
df_inflation <- data.frame(Year, nominal_prices)
df_inflation$in_2020_dollars_factor <- adjust_for_inflation(nominal_prices, Year, "US", to_date = 2020)

```


```{r gathering enterprises tickers  - good for interactive}

min_year= 1970
max_year = 2020
            
            
              
              cat("\f")
              
              # gather enterprises' tickers
              
              portfolio_tickers <- unique(my_data$Tickers)
              
              extra_tickers <- c("FRT","PEP")
              tickers<-c(portfolio_tickers,extra_tickers)
              
              # set time interval for study:
              
              #tini=as.Date("2000-01-01")
              tini=as.Date(paste(min_year,"-01-01",sep=""))
              #tend=floor_date(Sys.Date(),"year")
              tend=as.Date(paste(max_year,"-12-31",sep=""))
              
              yini=as.numeric(format(as.Date(tini, format="%Y/%m/%d"),"%Y"))
              yend=as.numeric(format(as.Date(tend, format="%Y/%m/%d"),"%Y"))
              yinterval=yend-yini
              
              # get data of the stock trend for all enterprises
              result_aux<-BatchGetSymbols(tickers,
                                      first.date=tini,
                                      #first.date=input$years_analysis[1],
                                      last.date=tend,
                                      #last.date=input$years_analysis[2],
                                      freq.data="daily")
              
              result<-as.data.frame(result_aux$df.tickers)
              
              result$mon_yr = format(result$ref.date, "%Y-%m") 
              
              #result <- result %>% group_by(mon_yr) %>% filter(ref.date == max(ref.date))
              
              rm(result_aux)
              

              ### SP500 history
                            SP500_trend <- as.data.frame(BatchGetSymbols("^GSPC",
                                      first.date=tini,
                                      last.date=tend,
                                      freq.data="daily")
                                                        ) %>% 
                                  select(Ticker = 1, Date = 13, Price = 10)
```



```{r get all dividends for sp500 - good for interactive}


df_sp500 <- GetSP500Stocks()

 #unique(df_sp500$GICS.Sector)
 
  #unique(df_sp500$GICS.Sub.Industry)


selected_sp500<-filter(df_sp500, GICS.Sector=="Real Estate") %>% select(Tickers)

                     
  #Select the ones in the portfolio + the ones included in the specified SP500 sector
  #tickers<-c(unique(my_data$Tickers),selected_sp500$Tickers)

```





```{r user defined functions}



### Get the dividends grouped by year and company of the given Tickers ###
Tickers_to_Dividends <- function(enterprises) {


#pre-define an empty DF
df <- data.frame(year=numeric(),
                 Div=numeric(), 
                 Enterprise=character(), 
                 stringsAsFactors=FALSE) 


for (k in 1:length(enterprises)) {
   
      a=getDividends(enterprises[k] )
      #a=getDividends(enterprises[1] )
      
   
      
      if ( length(a)==0) { #it will skip the iteration if getdividends does not find any records
          next
      }
      
      
      a <- data.frame(date=index(a), coredata(a))
      colnames(a) <- c("Date","Div")
      a$Enterprise <- replicate(nrow(a), enterprises[k])
    
    
      #group by year
      a["Year"]<-format(as.Date(a$Date, format="%d/%m/%Y"),"%Y")
      a=aggregate(data=a,cbind(Div) ~ Year + Enterprise, FUN=sum)
    

    a <- head(a, -1)       

    
     df <- rbind(df,a)

}


  
  df["Year"]<- as.numeric(df$Year)

 
  
  
  return(df)
}



#Get dividends of the selected tickers

total_div=Tickers_to_Dividends(tickers)

df["Year"]<- as.numeric(df$Year)

ggplot(data = total_div, aes(x = Year, y = Div, color = Enterprise))+ geom_line()

#to agregate per year all the dividends of the companies of the selected sector of the SP500 and then get their dividends
selected_sp500<-filter(df_sp500, GICS.Sector=="Industrials") %>% select(Tickers, Company)

df77=Tickers_to_Dividends(selected_sp500$Tickers)
  ggplot(data = df77, aes(x = Year, y = Div, color = Enterprise))+ geom_line()
  
  
  df88 = aggregate(data=df77,cbind(Div) ~ Year, FUN=sum)
  
   ggplot(data = df88, aes(x = Year, y = Div))+ geom_line()

```


```{r dashboard interactive}




#library(rstudio/shiny)

## Only run this example in interactive R sessions
if (interactive()) {
  # table example
  shinyApp(
    
    ui = fluidPage(
      #theme = shinytheme("spacelab"),
  
  titlePanel("Stock Returns Interactive"),
  
    ### SIDE BAR PANEL
  sidebarPanel(
                tags$style(".well {background-color:#edf7ff;}"),
              
                            sliderInput("Input_USD", "USD/Monthly invested during the period",
                            min = 0, max = 5000, value = 1000,width = "90%"),
                
                #https://shiny.rstudio.com/reference/shiny/1.6.0/selectInput.html
                        #   selectInput("linear_log_growth", "Choose which stocks to display:", 
                        #   list("All","Growth","Log")
                        # ),
                
                
                #dividends policy
                
                selectInput("check_div_policy", "Choose which dividend's policy check:", 
                          #list("JNJ","PG")
                          #c(as.character(names(total_div))[-1]) #ALL BUT THE FIRST ONE
                          #list(enterprises)
                           unique(total_div$Enterprise)
                          
                        ),
                
                      # slider range - https://shiny.rstudio.com/gallery/slider-bar-and-slider-range.html
                            sliderInput("years_analysis", label = h3("Years"), min = min_year, 
                              max = max_year, value = c(2000, 2020)),
                        
                            br(),
                            sliderInput("expected_returns", "Expected future returns",
                            min = 0, max = 20, value = 5,width = "90%"),
                            sliderInput("expected_inflation", "Expected future inflation",
                            min = 0, max = 30, value = 4,width = "90%"),
                
                            br(),
                            br(),
                          
                            # sliderInput("dividend_missed_opportunities", "Dividends - vista gorda",
                            # min = 0, max = 10, value = 1,width = "90%"),
                            # 
                            # sliderInput("dividend_missed_percentage", "Dividends - missed by X %", #when selected to 1, if there was not an increase in dividend value, its considered as a miss, if selected as 0,9, and few months the dividend would not increase/be at least 90% of its previous value, it would still passing our dividend test.
                            #min = 0, max = 1, value = 1,width = "90%"),
                
                                            
                            br(),
                            br(),
                
                            selectInput("sp500_sector", "Choose which SP500's sector to compare with:", 
                            unique(df_sp500$GICS.Sector),
                            # selectInput("sp500_company", "Choose which SP500's company:",
                            # )
                           
                          
                          
                            ),
                
                            
                            #checkboxInput("use_daily", label="Use daily compounding", value = FALSE, width = NULL),
                          
                
                
     
             ),
  
  mainPanel(

      fluidRow(
                column(12,
                
                  br(),
                  plotlyOutput("Graph_stock_trend"),
                  
                  br(),
                  plotlyOutput("Graph_onebuy_portoflio"),
                  plotlyOutput("Graph_dividends_portoflio"),
                  
                  
                  br(),
                  tableOutput('backtesting'),
                  #tableOutput('table_sp500_and_portfolio'),
                  
                  
                  br(),
                  br(),
                  
                  textOutput("introtext_dividends"),
                  verbatimTextOutput("Div_years_missed"),
                  
                  plotlyOutput("Graph_dividends_policy"),
                  

                  

                  
                  tableOutput('table_dividends_years'),
                  tableOutput("table_sp500_selected"),
                  #plotlyOutput("Graph_selected_sp500_dividends"),
                  
                  

                )
              )
            )
    ),
    
    
    
    
    server = function(input, output) {

      
    
      ### Dataframes ###
      
     df_inter_results <- reactive({

              return(
                  filter(result,
                         year(ref.date) >= input$years_analysis[1] &
                           year(ref.date) <= input$years_analysis[2])
                     )
      
                        })
     
     df_interactive_total_divs <- reactive({
       
       
              df_c <- filter(total_div,
                         Enterprise == input$check_div_policy &
                         Year >= input$years_analysis[1] &
                           Year <= input$years_analysis[2])
       

           # c<- total_div %>% filter(Enterprise == "MSFT" & 
           #                            Year >= 2004 &
           #                            Year <= 2020) %>% select(Div)
           

          # length( diff(c$Div))
          #diff(c$Div)
           
          #diff(c$Div) < 0 #get the ones missed only (the <0 differences between 2 consecutives Yearly Dividends)

              df_c$Colour <-  c("FALSE",diff(df_c$Div) < 0)
              
              df_c$Colour[df_c$Colour=="TRUE"] <- "Red"
              df_c$Colour[df_c$Colour=="FALSE"] <- "Green"
       
       
         return( df_c )
       
     })
     
     
      df_inter_sp500 <- reactive({ #used in the table table_sp500_selected and for the reactive dataframe df_inter_sp500_dividends
        
                        
                        
                #df_sp500 <- GetSP500Stocks()
                
                 #unique(df_sp500$GICS.Sector)
                 
                  #unique(df_sp500$GICS.Sub.Industry)
                
                #selected_sp500<-filter(df_sp500, GICS.Sector=="Industrials") %>% select(Tickers, Company)
                selected_sp500<-filter(df_sp500, GICS.Sector==input$sp500_sector) %>% select(Tickers, Company)

      
                
                
                        })
      
      
      df_inter_sp500_dividends <- reactive ({ #all dividends of the companies belonging to the selected sp500 sector
        
        df77=Tickers_to_Dividends(df_inter_sp500()$Tickers)
               # ggplot(data = df77, aes(x = Year, y = Div, color = Enterprise))+ geom_line()
               
                aggregate(data=df77,cbind(Div) ~ Year, FUN=sum)  
        
        
      })
      
      df_buy_n_hold_portfolio_value <- reactive ({ ## use for Graph_selected_sp500_dividends
        
        
        filtered_results <-filter(result,
               ticker %in% portfolio_tickers)
        
        
        #unique(filtered_results$ticker)
        
        #unique(result$ticker)
        
        
        filtered_results <- filtered_results %>% 
      left_join(my_data %>% select (Tickers, Amount), by = c('ticker' = 'Tickers')) #merging with the amount of stocks (one time buy)
        
        filtered_results$Value = filtered_results$price.close * filtered_results$Amount #the value of each stock in the portolio in a given date
        
        
        
       
        
        
        Portfolio_df = aggregate(data=filtered_results,cbind(Value) ~ ref.date, FUN=sum) #the selected Portfolio Tickers with their Value times the amount of shares that were allocated
        
         Portfolio_df <- Portfolio_df %>%
       left_join(SP500_trend, by = c('ref.date' = 'Date'))  %>% select(ref.date,Value, Price)
        
        #add sp500 data for comparisong
        
        
        
       #  Portfolio_df <- Portfolio_df %>%
       # left_join(SP500_trend , by = c('Tickers' = 'Ticker'))
        
      })

      
          df_backtesting_investments <- reactive ({ # returns when investing a certain amount in a selected porfolio
            
            
            df_monthly_buy <- data.frame(mon_yr=character(), #prepare a DF to include all the monthly acquisition
                 ticker=character(), 
                 Bought=numeric(), 
                 stringsAsFactors=FALSE) 
            
             result_eom <- result %>%
                          filter(year(ref.date)>= input$years_analysis[1]
                                 & year(ref.date)<= input$years_analysis[2]) %>% 
                          group_by(mon_yr) %>% filter(ref.date == max(ref.date)) #Take the investment date as the last day of each month
             
             result_eom$yr <- as.numeric(format(result_eom$ref.date,'%Y'))
             
             
             result_eom <- result_eom %>% 
                              left_join(df_inflation %>% select (Year, in_2020_dollars_factor), by = c('yr' = 'Year'))
             
             
             #investing in the selected period the selected amount with the variable ''Input_USD'' distributed equally across the portfolio's                     tickers
             
             
             
             for(i in 1:length(unique(result_eom$mon_yr))) {
               
               
               ttt =  result_eom %>% 
                                filter(grepl( unique(result_eom$mon_yr)[i], mon_yr )) 
                                #filter(stringr::str_detect(mon_yr, '1970-01') )
               
               #buying_power <- 1000/ttt[1,"in_2020_dollars_factor"]/nrow(ttt)
               buying_power <- input$Input_USD/ttt[1,"in_2020_dollars_factor"]/nrow(ttt)
               ttt$Bought <- as.numeric(buying_power)/ttt$price.close 
               
               ttt <- ttt %>% select (mon_yr,ticker,Bought)
               
                df_monthly_buy <- rbind(df_monthly_buy,ttt)
                  
                
                  
             }
             
             
             df_monthly_buy = aggregate(data=df_monthly_buy,cbind(Bought) ~ ticker, FUN=sum)
             
             
             ## Current Dividends (as per the latest year selected in the UI, matched with the amount of stocks at the portfolio at that time)
             
               df_monthly_buy <- df_monthly_buy %>% 
                              left_join(total_div[total_div$Year == 2020,] %>% select(Enterprise, Div), by = c('ticker' = 'Enterprise'))
            
              df_monthly_buy$Yearly_Income <- df_monthly_buy$Bought * df_monthly_buy$Div
              
              df_monthly_buy <- rbind(df_monthly_buy, c("Total Yearly", "-x-", "-x-", sum(as.numeric(df_monthly_buy$Yearly_Income))))
              
              df_monthly_buy <- rbind(df_monthly_buy, c("Total Monthly (Net)", "-x-", "-x-", sum(as.numeric(df_monthly_buy$Yearly_Income))/2*0.7/12)) #/2 since it the sum was already performed in the previous line
              
              
              return(df_monthly_buy)
              #sum(df_monthly_buy$Income)
            
            
          })

      ###### GRAPHS ###### 
        
      
          output$Graph_dividends_policy<- renderPlotly({
            
            
                 ggplotly(
                        ggplot(df_interactive_total_divs()
                               , aes(x=Year, y=Div)) +
                         geom_bar(stat = "identity", colour=df_interactive_total_divs()$Colour)
                         #geom_bar(colour=df$col)
                        + ylab(input$check_div_policy)
                        
                    ) 
    
    
          })
          
        
            output$Graph_stock_trend <-renderPlotly({
               
                  
              #option 1#
                       ggplotly(

             
                          ggplot(subset(df_inter_results(),ticker!="AMZN"),
                                  aes(x=ref.date, y=price.close, group=ticker))
                           + geom_line(aes(colour = ticker)) +
                            xlab("Date") + ylab("USD") + ggtitle("Selected Tickers Value")
                        )
              
             
                                            }) 
            
            
            
              output$Graph_onebuy_portoflio<-renderPlotly({ #Plotting the portfolio value vs SP500 over time
               
                       # ggplotly(
                       #    ggplot(df_buy_n_hold_portfolio_value(),aes(x=ref.date, y=Value)) +
                       #      geom_line() + ggtitle("Portfolio's Historical Value")
                       #  )
                
                
                      #               ggplot(df_buy_n_hold_portfolio_value(), aes(ref.date)) + 
                      # geom_line(aes(y = Value, colour = "Portfolio Value")) + 
                      # geom_line(aes(y = Price, colour = "SP500")) +
                      # xlab("Date") + ylab("USD") + ggtitle("Portfolio's Historical Value")
                
                
                 # Year >= input$years_analysis[1] &
                 #           Year <= input$years_analysis[2]
                
                   ggplot(subset( df_buy_n_hold_portfolio_value(),
                                  year(df_buy_n_hold_portfolio_value()$ref.date)>= input$years_analysis[1] &
                                  year(df_buy_n_hold_portfolio_value()$ref.date)<= input$years_analysis[2]),
                          aes(ref.date)) + 
                      geom_line(aes(y = Value, colour = "Portfolio Value")) + 
                      geom_line(aes(y = Price, colour = "SP500")) +
                      xlab("Date") + ylab("USD") + ggtitle("Portfolio's Historical Value")
                 
                 
                 
              
             
                                            })
              
              
               output$Graph_dividends_portoflio<-renderPlotly({
                 
                 
                  df_c <- filter(total_div,
                         Year >= input$years_analysis[1] &
                           Year <= input$years_analysis[2])
       

              df_c$Colour <-  c("FALSE",diff(df_c$Div) < 0)
              
              df_c$Colour[df_c$Colour=="TRUE"] <- "Red"
              df_c$Colour[df_c$Colour=="FALSE"] <- "Green"
                 
                                                          ggplotly(
                                                                  ggplot(df_c,
                                                                         aes(x=Year, y=Div)) +
                                                                        geom_bar(stat = "identity", colour=df_c$Colour) +
                                                                             ggtitle("Portfolio's Tickers Dividends")
                                                                )
                                                               
                                                             })
              
              
              
              
              output$Graph_selected_sp500_dividends<-renderPlotly({
               
                
                       ggplotly(
                               ggplot(df_inter_sp500_dividends(),aes(x=Year, y=Div)) + geom_bar(stat = "identity")
                               )
              
             
                                            }) 
              
              
              
            
            
            ##### TABLES ######
          
output$table_dividends_years <- renderTable({
   
  
  df_interactive_total_divs() %>% select(Year,Div)
  })


output$table_sp500_selected <- renderTable({

  
  df_inter_sp500()
  })


output$table_sp500_and_portfolio <- renderTable({

  
  df_buy_n_hold_portfolio_value()
  })





output$backtesting <- renderTable({

  
  df_backtesting_investments()
  })


### TEXT

          
        output$introtext_dividends <- renderText({ 
    "The selected company have missed the dividend increase (Years):"
                                        })          
                    
          output$Div_years_missed <- renderPrint({ 
            
            
           
           c<- total_div %>% filter(Enterprise == input$check_div_policy & 
                                      Year >= input$years_analysis[1] &
                                      Year <= input$years_analysis[2]) %>% select(Div)
                    
           
           count(diff(c$Div) < 0)[2,2]#get the ones missed only (the <0 differences between 2 consecutives Yearly Dividends)
           
                                   })  
          
      

         
           
          
      
                        } #server
  ) #shinyapp
  
  
} #if interactive





```